### ISSUE TITLE
great work, waiting for the python code

### ISSUE THREAD

**Issue by kli-casia** [ssarfraz/FINCH-Clustering#1]

**Comment by MDR-EX1000** [comment]
Will there be official python support?  Seems easy to implement

**Comment by ssarfraz** [comment]
@MDR-EX1000 :+1:  try it then! Would be great. Since data is there,  would be easy to validate your implementation wrt to timing and performance etc.

I am a bit busy these days, will probably spent some time begining April (hopefully), and put it here, in any case.

**Comment by chenxofhit** [comment]
@ssarfraz great work, please carry on ...

**Comment by kli-casia** [comment]
@ssarfraz   I test your algorithm on my own data set, it works very well. It would be best if you kindly release the python code, this will help more people, since not everyone can afford matlab

**Comment by ssarfraz** [comment]
Hello, Python code is up now. see the read me for details.
