### ISSUE TITLE
about output

### ISSUE THREAD

**Issue by cLEARLoVE00** [ssarfraz/FINCH-Clustering#11]
Thank your opened code,I want to know what mean about output of 'C', It is a N*2 array，what which is cluster label？ I found about my data get bad result ,I want to reason.

**Comment by ssarfraz** [comment]
I suggest read the usage here carefully https://github.com/ssarfraz/FINCH-Clustering/blob/master/README.md#usage and go through the example given there on clustering STL-10 data.
