### ISSUE TITLE
Matching problem of TW-FINCH

### ISSUE THREAD

**Issue by LUJUNYIhhh** [ssarfraz/FINCH-Clustering#14]
It is amazing that this unsupervised clutering method outperforms other paradigms on five challenging action segmentation datasets. However, some details puzzle me a lot, just about how to map the obtainded segments with different action labels (including background) using Hungarian algorithm. It would pretty appreciate if these problems would be explained.

**Comment by HenryPengZou** [comment]
Same question here. I am also very confused about how to use Hungarian algorithm in the action segmentation setting. Could you help give some explanation on it? Thanks
