### ISSUE TITLE
TWFinch code missing FS "Eval" option; unable to reproduce accuracy

### ISSUE THREAD

**Issue by hayab** [ssarfraz/FINCH-Clustering#17]
Hello, thank you for posting the code and data for the TWFinch paper.

The code seems to be missing an option to run the FS "Eval" dataset.
I've made a logical change to your code (below) to load this dataset, but am unable to reproduce the accuracy in the paper, which was reported as `MoF= 71.1%`.

The following change to `TW-FINCH/util_fns/read_video.m` produces an accuracy of `MoF:= 66.7%`:
```
 elseif strcmp(Dataset, 'FS')
    map=readtable(fullfile(mapping_path, 'mappingeval.txt'));
    map2=table([1:numel(map.Var2)]', 'RowNames', map.Var2);
    gt_label_str=table2cell(readtable(fullfile(gt_path, vid_name), 'Delimiter', '#', 'ReadVariableNames',false));
    gt_label_frame=table2array(map2(gt_label_str,1));
```

I would appreciate any guidance on what might be wrong. Thank you.

**Comment by ssarfraz** [comment]
hi, have added the eval mode , to do this on 50Salads you can set it to true on this line here https://github.com/ssarfraz/FINCH-Clustering/blob/a1de04e0483af95cc2023865572e4eeb208734fb/TW-FINCH/util_fns/action_seg.m#L30

The evaluation in eval mode only  groups some labels and we need to use those when we are evaluating the obtained clusters. It is a bit of work to properly map between the original mapping and the eval mode mapping.  you can see the respective function eval_fs in the evaluation folder to see how it is done.
