### ISSUE TITLE
errors when run the  run_on_dataset.m 

### ISSUE THREAD

**Issue by Liushilin** [ssarfraz/FINCH-Clustering#18]
hello,thank you for posting the code for the TWFinch and great work！I have tried to reproduce the results,but I meet some problems when I run the  run_on_dataset.m.

I downloaded the data and put it under E:\FINCH-Clustering-master\TW-FINCH\,
then I run the script `tw_finch = true
Result = run_on_dataset('50Salads', tw_finch, 'E:\FINCH-Clustering-master\TW-FINCH\Action_Segmentation_Datasets');`
the error is as follows

![捕获144](https://user-images.githubusercontent.com/50707193/144541157-9db842d8-ddf3-47c0-b45e-d4588c97bc6d.PNG)

**Comment by Liushilin** [comment]
![捕获145](https://user-images.githubusercontent.com/50707193/144542420-9bb455e1-4958-494d-8597-5e3611e9e55c.PNG)

**Comment by ssarfraz** [comment]
Looks like you need to check if the path is correct.  In your path " E:\FINCH-Clustering-master\TW-FINCH\Action_Segmentation_Datasets" there should be data folder '50 Salads' etc .  Anyways its something which is not related to code.

**Comment by Liushilin** [comment]
Thank you very much for your reply,I add breakpoint at line 27
`gt_label_str=table2cell(readtable(fullfile(gt_path, vid_name), 'Delimiter', '#', 'ReadVariableNames',false));` and run the file,
the value of `fullfile(gt_path, vid_name)` is as below
![捕获146](https://user-images.githubusercontent.com/50707193/144582396-993c029b-6eb8-4a8b-9d37-04aded5f061a.PNG)
the path form is obviously wrong,I think it maybe the reason why it can't find the file.How can I solve it?

**Comment by ssarfraz** [comment]
In the line you posted above the variable vid_name should just be 'rgb-01-1'. Have you made any changes in the code you forgot to revert back? this should not happen and I can run it just fine, may be try after cloning the repo again.

**Comment by Liushilin** [comment]
Thanks for your advice,I clone the repo again and I'm sure that I have never changed the code,but the error is still exists.
Then I find the values of buf and vid_name are as below
![捕获149](https://user-images.githubusercontent.com/50707193/144701833-0a452eb7-603f-490f-afab-6453f880e573.PNG)
so I add code`vid_name = vid_name(end-7:end);` after line 8`vid_name = buf{end}; vid_name=vid_name(1:end-4);`,
![捕获148](https://user-images.githubusercontent.com/50707193/144701783-7d19b458-f83c-425d-b161-5c3725ddf75f.PNG)
Then it works

**Comment by ssarfraz** [comment]
Ah I see the problem now,  You r on Windows and it uses backslash "\" in paths. So to handle this in line 6 in read_video.m you should switch the forward slash "/" to backward "\"    `buf = textscan(files{video},'%s','Delimiter','\')`  .

It should work then, you current way is not proper and it may fail on other datasets where the filenames have different lengths.

**Comment by ssarfraz** [comment]
Also change the forward slash to backward on line https://github.com/ssarfraz/FINCH-Clustering/blob/7916c95eca76c56787d228f97059f63a0a5213f7/TW-FINCH/run_on_dataset.m#L38 . So it run properly on MPII_Cooking as well

**Comment by Liushilin** [comment]
Thank you very much! The problem has been solved.
Next I want to test on my own dataset,but I'm confused about how to make the dataset.
I read the paper "Unsupervised learning of action classes with contin-
uous temporal embedding",but he only mentions that he extracts frame-wise features using improved dense trajectories .
Do I just need to extract the iDT features and make the corresponding ground-truth、mapping folders?
