### ISSUE TITLE
There is a bug when using pynndescent.NNDescent

### ISSUE THREAD

**Issue by Classmate-Huang** [ssarfraz/FINCH-Clustering#19]
Nice work! 

When my data volume is very large, I will use the "NNDescent" in the "pynndescent" library according to the "Python" code, and then an error will occur.

![image](https://user-images.githubusercontent.com/59324642/147719106-ca0b0a34-315a-4d39-8803-5ee8a07cc3cd.png)

my “pynndescent” version is ‘0.5.5'. how to fix it?

Looking forward to your reply, thanks.

**Comment by ssarfraz** [comment]
hi thanks for letting me know. have fixed it. please clone again .

**Comment by Classmate-Huang** [comment]
It works, thanks! ^_^!
