### ISSUE TITLE
Any random factors in this algorithm?

### ISSUE THREAD

**Issue by MDR-EX1000** [ssarfraz/FINCH-Clustering#2]
Got different results for different trials in my experiments ...

**Comment by ssarfraz** [comment]
You must be using flann KD tree, thats the only random factor since it may output a different first neighbor each time if you dont fix the random seed or save its index file somewhere for reuse. 

You should get the exact same result if you r computing first neighbors through exact distance.

**Comment by MDR-EX1000** [comment]
@ssarfraz  Thanks for your reply . BTW , which one do you recommend for flann param "algorithm"?  If the result is good enough, i don't mind the random factors.

**Comment by ssarfraz** [comment]
This is something of your choice, FINCH only needs integer indices of first neighbour form whatever approximate or exact distance method you employ.  However, almost all of the current approximate methods may have some randomness in them. For now, I would say, finch should not be too much off in terms of cluster purity in the end with these different initial random estimates of approx methods., so KD tree should be fine, you can just change/increase its params (e.g. trees or checks etc) to get more stable/accurate estimates at the expense of the time it spends. 
Probably also checkout some of the recent proposals in the ANN search algos (just google), though a nice paper to understand current ANN methods and their reasoning is https://arxiv.org/abs/1806.09823 . 

But this is something, I am also thinking about nowadays, to comeup with some better ann search that do not suffer from these problems. lets see how it goes  :-)

**Comment by MDR-EX1000** [comment]
@ssarfraz  Thanks!

**Comment by kli-casia** [comment]
@ssarfraz  Is FINCH sensitive to outliers?

**Comment by ssarfraz** [comment]
I think outliers would be grouped in some cluster anyways, as FINCH can not handle singletons as we discussed in the paper. but in terms of cluster purity this should not be a problem unless you wanna use it for outlier detection (that it probably cannot do).

**Comment by kli-casia** [comment]
thanks
