### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 4 dimensions(s) and the array at index 1 has 2 deminesion (s).

### ISSUE THREAD

**Issue by sijan67** [ssarfraz/FINCH-Clustering#20]
Hi,  I tried to convert my video into a numpy array as method shown here (https://stackoverflow.com/questions/67644826/how-to-convert-a-video-to-a-numpy-array) . And now when I pass it as a input to the function as FINCH(data, req_clust=K, tw_finch=True) I am getting :
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 4 dimensions(s) and the array at index 1 has 2 deminesion (s). The shape of my data right now is (928, 108, 108, 3)

 How do I fix this? Is there any other  method to get feature vector of a video ? I really appreciate the response !

**Comment by ssarfraz** [comment]
The input data should be two dimensional i.e. N x d i.e preferably you need to represent each frame of the video with some feature vector (e..g, by using any pretrained video CNN model such as I3D etc,). If you want to just cluster frames based on raw pixels then  just reshape your input data to 928 x 34992
