### ISSUE TITLE
TW-FINCH feature extraction method

### ISSUE THREAD

**Issue by Liushilin** [ssarfraz/FINCH-Clustering#21]
hello,thanks for your work!I'm sorry but this problem has been bothering me for a long time.For TW-FINCH,do the frame-wise features can only be extracted by iDT(your paper mentioned),or it can also be extracted by other CNN methods such as I3D？Will the methods affect the clustering results?

**Comment by ssarfraz** [comment]
sure you can use any feature extractor (e.g I3D etc,.) to cluster, the results may vary depending upon the quality of the features used
