### ISSUE TITLE
element of adjacent matrix may greater than 1

### ISSUE THREAD

**Issue by wjlyclll** [ssarfraz/FINCH-Clustering#23]
thanks for this amazing and practical algorihtm 
when I browse the python ver code, I find the element of adjacent matrix may greater than 1 as below

csr_matrix in python.finch.py line45
0, 0, 0, 0, 1
0, 0, 0, 0, 1
0, 1, 0, 0, 0
0, 0, 0, 0, 1
0, 1, 0, 0, 0
adjacent matrix in line50
0, 1, 0, 1, 1
1, 0, 1, 1, 2
0, 1, 0, 0, 1
1, 1, 0, 0, 1
1, 2, 1, 1, 0

maybe this will impact the value of min_sim in hierarchy cluster line155

**Comment by ssarfraz** [comment]
hi these are just static links, may as well be 1 (delivers the same connected components in graph)- have no impact on performance.

**Comment by wjlyclll** [comment]
> hi these are just static links, may as well be 1 (delivers the same connected components in graph)- have no impact on performance.

thanks for your reply. I know the element 2 will not impact the connectivity in graph now. I just wonder whether the doulbed value of min_sim (min_sim = np.max(orig_dist * adj.toarray()) when the max original distance corresponds with element 2 in adjacent matrix) will impact the successive hierarchy clustering.

**Comment by ssarfraz** [comment]
Ah yes it would have a little impact, however not crucial on eventual cluster purity.  This early_stop criterion is also optional, you may as well run without it.

**Comment by wjlyclll** [comment]
> Ah yes it would have a little impact, however not crucial on eventual cluster purity. This early_stop criterion is also optional, you may as well run without it.

Thanks for your kind reply. This algorihtm is very helpful.
