### ISSUE TITLE
Unable to replicate numbers

### ISSUE THREAD

**Issue by pulkitkumar95** [ssarfraz/FINCH-Clustering#27]
Hey,

I was trying to replicate the numbers presented in the paper with the features provided and my numbers seem to be a bit on the lower side. Without changing anything, I ran the python version of the code, and what i noticed was on breakfast I am getting an MOF of 60.1 whereas the reported number is 62.7. Similarly for MPII, I am getting 41.51 but reported number is 42.0 (Though very minor). Is there a reason for this discrepancy?

**Comment by ssarfraz** [comment]
hi, please check matlab implementation for exact reproduction of reported numbers.  there may be some numpy precision issues in python.
