### ISSUE TITLE
how to handle dataset that is too large to be loaded in the memory?

### ISSUE THREAD

**Issue by kli-casia** [ssarfraz/FINCH-Clustering#3]
Suppose I have a dataset of 3000w items, each item is a 2048-d vector.
Thanks

**Comment by ssarfraz** [comment]
what exactly is the size,  didnt get 3000w? in principal, if you cant load the data in the memory, you need to use/develop some mechanisms to handle this, e.g. data parallel /map-reduce implementations etc,. With FINCH it should be more practical, as you can compute the first neighbors using e.g., ANN methods that process data by mapping it to hash codes and then use these to load into memory and/or compute 1-NN.  One can imagine how you can build a processing chain with data read/write operations to handle  very large data.

**Comment by kli-casia** [comment]
thanks
