### ISSUE TITLE
If the way F1-scores is calculated is different in matlab and python

### ISSUE THREAD

**Issue by April-lyl** [ssarfraz/FINCH-Clustering#30]
When I was doing the experiment, the f1-scores in python always lower than matlab, but the other metric are  always similar. For example, as for Breakfast:
![20230224172246](https://user-images.githubusercontent.com/56187413/221144137-c01e4b32-d84e-4b31-8c9b-0d4c4d9bbe6b.png)
![20230224172403](https://user-images.githubusercontent.com/56187413/221144166-0af18bad-9020-4212-8c27-e75936b64444.png)

**Comment by ssarfraz** [comment]
could be because  sklearn f1 score is computing it with average='macro'. Can you check setting this to 'micro' or 'weighted'. i think here since we don't predict exact number of classes, it should be global (like in matlab which computes these on conf mat).

**Comment by April-lyl** [comment]
setting this to 'micro' and 'weighted' has no effect. I replicated the matlab function 'compute_clustScores' in python, it can be work. Although Nan appears in numpy operation, the program may report RuntimeWarning, this problem has no effect.

**Comment by ssarfraz** [comment]
yeah matlab f1 score should be akin to sklearn's f1 with average='macro'.  i am not sure what could be causing this,, will try to have a more closer look later in few weeks time. In case you figure it out then please do share here.
