### ISSUE TITLE
How to get the midpoint hit criterion for the MPII?

### ISSUE THREAD

**Issue by April-lyl** [ssarfraz/FINCH-Clustering#31]
All I konw is how to get the percision and recall. But I don't know how to get the midpoint hit, and they are different.

**Comment by ssarfraz** [comment]
hi,
we have used the official evaluation toolkit from the MPII auhtors (matlab) here. you can also have a closer look at their paper to understand it better.
 http://human-pose.mpi-inf.mpg.de/#evaluation
