### ISSUE TITLE
`sklearn` is still a dependency in `setup.py`

### ISSUE THREAD

**Issue by falcaopetri** [ssarfraz/FINCH-Clustering#32]
Commit b508b1a intended to remove `sklearn` dependency, but actually removed `scipy`. You can check the commit's diff [here](https://github.com/ssarfraz/FINCH-Clustering/commit/b508b1a8ada5ddb90d60a8b63b0e5ecb0a78ea4b#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L28).

`scipy` is still installed since it's a dependency of `scikit-learn`, but we also get the deprecated `sklearn` package.

This means that the problem from #29 still affects `finch-clust==0.1.8`. We can check it by doing the following (based on [How to test whether a package will be affected by the sklearn deprecation](https://github.com/scikit-learn/sklearn-pypi-package#how-to-test-whether-a-package-will-be-affected-by-the-sklearn-deprecation)):

```bash
SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=False \
    pip install finch-clust==0.1.8
```

**Comment by ssarfraz** [comment]
Thanks a lot for letting me know, it is fixed now!
