### ISSUE TITLE
IndexError when req_clust > num_clust

### ISSUE THREAD

**Issue by saveli** [ssarfraz/FINCH-Clustering#33]
I call finch using 
`cluster_partition, n_part_clust, part_labels = FINCH(data, req_clust=2)`

and receive this error
```
line 185, in FINCH
    req_c = req_numclust(c[:, ind[-1]], data, req_clust, distance, use_ann_above_samples, verbose)
IndexError: list index out of range
```

My best guess is, that there is only one cluster, so the condition `v >= req_clust` is never fulfilled in `ind = [i for i, v in enumerate(num_clust) if v >= req_clust]`, thereby the index list is empty, thereby `ind[-1]` is out of range.

What is the implication and how to best deal with this?

**Comment by ssarfraz** [comment]
Hi, yes, looks like in your case the FINCH fist partition has only 1 cluster? In general it wont provide you more clusters than you have in the very first partition. while I will add the necessary error handling, for now you can check the impact of using different distance metrics, it supports one of ['cityblock', 'cosine', 'euclidean', 'l1', 'l2', 'manhattan']. may be one of these will not cause to merge your data into one cluster in the very first step. As for having a better way to deliver clusters that are more than the FINCH first merge step, it is also possible but requires more though and time to think of an algorithm that can break some clusters to achieve this.

**Comment by saveli** [comment]
I did try different metrics, it was the same error for both manhattan and cosine, but euclidean did work. I could do a loop to try the other metrics until no `IndexError` is raised, but there will be cases, where no metric works, I suppose.

If it helps, I can provide the data.

**Comment by ssarfraz** [comment]
sure , please provide the data, I can also have a look. however if first partition is already 1 cluster then it wont currently split it into two. In general if you first merge results into a single cluster, that means the data has very similar close points/samples which really should be in one cluster.

**Comment by saveli** [comment]
Data is [here](https://pastebin.com/7TF4XDPm), loadable with `numpy.loadtxt()`. Shape is `(42, 256)` and only `euclidean` has more than one cluster.

If data is not sepparable, it should not terminate with an exception, but maybe return a single cluster with a warning?

**Comment by ssarfraz** [comment]
yes, will push the necessary error handling shortly
