### ISSUE TITLE
Could you please provide the tool for visualizing the Figure 2?

### ISSUE THREAD

**Issue by vhientran** [ssarfraz/FINCH-Clustering#5]
Dear @ssarfraz ,
I am sorry for disturbing you, but could you please describe in more detail the tool or the source code you visualize the Figure 2 in your paper? Thank you so much!

**Comment by ssarfraz** [comment]
its a standard scatter plot. you can use pyplot.scatter (in python) or scatter (n matlab). For 2D toy examples don't forget to use euclidean distance.

**Comment by vhientran** [comment]
I got it. Thank you for your time.
