### ISSUE TITLE
how to estimate number of clusters

### ISSUE THREAD

**Issue by slchenchn** [ssarfraz/FINCH-Clustering#6]
I was wondering how to estimate number of clusters using FINCH after reading your paper, your method seems can always get the correct number of clusters, e.g., in Table 2.

**Comment by ssarfraz** [comment]
it returns few meaningful partitions of the data, where it it is likely that one of the partition will be close to the ground truth clusters. In table 2 we showed that on those data that was indeed the case. But it does not estimate one flat partition.  If you know nothing about what clusters your data might have, it is good to bear in mind that FINCH first few partitions are the most pure ones.

**Comment by slchenchn** [comment]
OK, thanks!
