### ISSUE TITLE
Why does edge (vertices are the most similar nodes of each other) have greater weight when compare with min_sim

### ISSUE THREAD

**Issue by seanM29** [ssarfraz/FINCH-Clustering#7]
thanks for your work!!! I love it very much!!
I want to know Why does edge (vertices are the most similar nodes of each other) have greater weight when compare with min_sim? 
In the src code, the weight of edge(vertices are the most similar nodes of each other) is 2, while others is 1 when compared with min_sim

**Comment by ssarfraz** [comment]
@seanM29 the weights of edges would be greater when they are directed and form loops, its just an output of the way clustering equation is implemented, however important to know is that FICNH does not use any edge weights, they may as well be all set to 1's (I leave this out to save some compute.. as it doesn't matter we just use all connected components irrespective of their weights). The comparison of min_sim is only optional (see the updated read me), it helps early exit and may  prove useful when your data is unbalanced. This however also can not be done when you are using approx NN (KD-tree)  to find the 1st nbr, only would run when using exact distance to compute 1st nbrs.
